//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftKinectWrapper {
    
    
    #region Component Designer generated code 
    public partial class ISpeechRecognition_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::MicrosoftKinectWrapper.@__ISpeechRecognition.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::MicrosoftKinectWrapper.ISpeechRecognition), typeof(global::MicrosoftKinectWrapper.ISpeechRecognition_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::MicrosoftKinectWrapper.ISpeechRecognition), typeof(global::MicrosoftKinectWrapper.ISpeechRecognition_))]
    internal sealed partial class @__ISpeechRecognition : global::java.lang.Object, global::MicrosoftKinectWrapper.ISpeechRecognition {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setup0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_startRecog1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSpeech2;
        
        private @__ISpeechRecognition(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::MicrosoftKinectWrapper.@__ISpeechRecognition.staticClass = @__class;
            global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_setup0 = @__env.GetMethodID(global::MicrosoftKinectWrapper.@__ISpeechRecognition.staticClass, "setup", "([Ljava/lang/String;)V");
            global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_startRecog1 = @__env.GetMethodID(global::MicrosoftKinectWrapper.@__ISpeechRecognition.staticClass, "startRecog", "()V");
            global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_getSpeech2 = @__env.GetMethodID(global::MicrosoftKinectWrapper.@__ISpeechRecognition.staticClass, "getSpeech", "()Ljava/lang/String;");
        }
        
        public void setup(string[] args) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_setup0, global::net.sf.jni4net.utils.Convertor.ParArrayStrongC2JString(@__env, args));
            }
        }
        
        public void startRecog() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_startRecog1);
            }
        }
        
        public string getSpeech() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, @__env.CallObjectMethodPtr(this, global::MicrosoftKinectWrapper.@__ISpeechRecognition.j4n_getSpeech2));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ISpeechRecognition);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setup", "setup0", "([Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "startRecog", "startRecog1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSpeech", "getSpeech2", "()Ljava/lang/String;"));
            return methods;
        }
        
        private static void setup0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle args) {
            // ([Ljava/lang/String;)V
            // ([LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.ISpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::MicrosoftKinectWrapper.ISpeechRecognition>(@__env, @__obj);
            @__real.setup(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, args));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void startRecog1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.ISpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::MicrosoftKinectWrapper.ISpeechRecognition>(@__env, @__obj);
            @__real.startRecog();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getSpeech2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MicrosoftKinectWrapper.ISpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::MicrosoftKinectWrapper.ISpeechRecognition>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.getSpeech());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::MicrosoftKinectWrapper.@__ISpeechRecognition(@__env);
            }
        }
    }
    #endregion
}
