//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftKinectWrapper {
    
    
    #region Component Designer generated code 
    public partial class SpeechRecognition_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::MicrosoftKinectWrapper.@__SpeechRecognition.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::MicrosoftKinectWrapper.SpeechRecognition), typeof(global::MicrosoftKinectWrapper.SpeechRecognition_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::MicrosoftKinectWrapper.SpeechRecognition), typeof(global::MicrosoftKinectWrapper.SpeechRecognition_))]
    internal sealed partial class @__SpeechRecognition : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__SpeechRecognition(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::MicrosoftKinectWrapper.@__SpeechRecognition.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SpeechRecognition);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setup", "setup0", "([Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "startRecog", "startRecog1", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSpeech", "getSpeech2", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "stop", "stop3", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSpeechRecognition0", "__ctorSpeechRecognition0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static void setup0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle args) {
            // ([Ljava/lang/String;)V
            // ([LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.SpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MicrosoftKinectWrapper.SpeechRecognition>(@__env, @__obj);
            ((global::MicrosoftKinectWrapper.ISpeechRecognition)(@__real)).setup(global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CString(@__env, args));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void startRecog1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.SpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MicrosoftKinectWrapper.SpeechRecognition>(@__env, @__obj);
            ((global::MicrosoftKinectWrapper.ISpeechRecognition)(@__real)).startRecog();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getSpeech2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MicrosoftKinectWrapper.SpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MicrosoftKinectWrapper.SpeechRecognition>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, ((global::MicrosoftKinectWrapper.ISpeechRecognition)(@__real)).getSpeech());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void stop3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.SpeechRecognition @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MicrosoftKinectWrapper.SpeechRecognition>(@__env, @__obj);
            @__real.stop();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSpeechRecognition0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MicrosoftKinectWrapper.SpeechRecognition @__real = new global::MicrosoftKinectWrapper.SpeechRecognition();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::MicrosoftKinectWrapper.@__SpeechRecognition(@__env);
            }
        }
    }
    #endregion
}
